#import "../fragments/HeroSectionFragment.gql"
#import "../fragments/FeatureSectionFragment.gql"
#import "../fragments/TestimonialSectionFragment.gql"
#import "../fragments/FaqSectionFragment.gql"
#import "../fragments/TeamSectionFragment.gql"
#import "../fragments/CarouselSectionFragment.gql"

query LandingPage{
    landingPage(id: 5) {
        __typename
        id
        path
        depth
        numchild
        translationKey
        live
        goLiveAt
        expireAt
        expired
        locked
        lockedAt
        title
        draftTitle
        slug
        contentType
        urlPath
        seoTitle
        showInMenus
        searchDescription
        latestRevisionCreatedAt
        pageType
        url
        searchScore
        body {
            id
            blockType
            field
            ...HeroSectionFragment
            ...CarouselSectionFragment
            ...FeatureSectionFragment
            ...TeamSectionFragment
            ...TestimonialSectionFragment
            ...FaqSectionFragment
        }
    }
}