# Generated by Django 5.0.1 on 2024-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_address_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="default_billing_address",
            new_name="default_factory_address",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="default_shipping_address",
            new_name="default_office_address",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
