# Generated by Django 5.0.1 on 2024-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0004_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("employer", "Employer")],
                max_length=50,
            ),
        ),
    ]
