---
- name: Deploy Django and Next.js application
  hosts: all

  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../src"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: rsync
    ansistrano_after_setup_tasks_file: "tasks/after-setup.yml"
    ansistrano_after_update_code_tasks_file: "tasks/after-update-code.yml"
    ansistrano_after_symlink_tasks_file: "tasks/after-symlink.yml"

    ansistrano_allow_anonymous_stats: no
  roles:
    - { role: ansistrano.deploy }

