---
- name: Installs python application on server (secret gen, db setup, nginx, uwsgi and pm2 config)
  hosts: all

  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../src"
    ansible_user: root

  tasks:
    - name: Generates secrets/passwords
      set_fact:
        secret_key: "{{ lookup('password', '/dev/null chars=ascii_letters length=80') }}"
        database_password: "{{ lookup('password', '/dev/null chars=ascii_letters length=40') }}"

    - name: Counts previous uwsgi apps
      shell: ls -1 /mnt/persist/uwsgi/conf.d/ | wc -l
      register: uwsgi_application_count

    - name: Counts previous pm2 apps
      shell: ls -1 /mnt/persist/nodejs/ | wc -l
      register: pm2_application_count

    - name: Makes sure python psql lib is available
      pip:
        name: psycopg2-binary

    - name: Creates directory for shared files
      file:
        path: "{{ ansistrano_deploy_to }}/shared"
        state: directory
        owner: deploy
        group: www-data
        mode: 0775
        recurse: yes

    - name: Creates .env file for Django
      template:
        src: files/.env.j2
        dest: "{{ ansistrano_deploy_to }}/shared/.env"
        owner: deploy
        group: www-data
        mode: 0664

    - name: Creates .env.next file for Next.js
      template:
        src: files/.env.next.j2
        dest: "{{ ansistrano_deploy_to }}/shared/.env.next"
        owner: deploy
        group: www-data
        mode: 0664

    - name: Creates postgres database
      postgresql_db:
        name: "{{ database_name }}"
        lc_collate: sv_SE.utf8
        lc_ctype: sv_SE.utf8
        template: template0

    - name: Creates postgres user
      postgresql_user:
        db: "{{ database_name }}"
        name: "{{ database_user }}"
        password: "{{ database_password }}"

    - name: Associate postgres user to database
      postgresql_privs:
        db: "{{ database_name }}"
        privs: ALL
        type: database
        role: "{{ database_user }}"

    - name: Adds postgis extension
      postgresql_ext:
        name: postgis
        db: "{{ database_name }}"

    - name: Creates uWSGI config
      template:
        src: files/uwsgi.ini.j2
        dest: "/mnt/persist/uwsgi/conf.d/{{ project_slug }}.ini"
        mode: 0664

    - name: Replaces default uwsgi conf with empty
      file:
        path: "/mnt/persist/uwsgi/conf.d/django.ini"
        state: absent

    - shell: echo "" > /mnt/persist/uwsgi/conf.d/django.ini

    - name: Copies nginx config
      template:
        src: "files/nginx.conf.j2"
        dest: "/mnt/persist/nginx/conf.d/{{ project_slug }}.conf"
        mode: 0664

    - name: Copies robots.txt
      copy:
        src: "files/robots.txt"
        dest: "{{ ansistrano_deploy_to }}/shared/robots.txt"
        owner: deploy
        group: www-data
        mode: 0664

    - name: Creates directory for pm2 config
      file:
        path: "{{ ansistrano_deploy_to }}/shared/pm2"
        state: directory
        owner: deploy
        group: www-data
        mode: 0775
        recurse: yes

    - name: Creates pm2 .yml file for next.js
      template:
        src: files/pm2_config.yml.j2
        dest: "/mnt/persist/nodejs/{{ project_slug }}.yml"
        group: www-data
        mode: 0664

    - name: Add wagtail cronjobs
      lineinfile:
        path: /mnt/persist/etc/crontab
        line: "0 * * * *  www-data {{ ansistrano_deploy_to }}/shared/venv/bin/python {{ ansistrano_deploy_to }}/current/src/manage.py publish_scheduled_pages"


