#import "../fragments/TestimonialBlockFragment.gql"
fragment TestimonialSectionFragment on TestimonialSection{
    heading
    description
    testimonials{
        ...TestimonialBlockFragment
    }
}