# Generated by Django 5.0.1 on 2024-03-04 12:48

import main.blocks.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_landingpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "carousel_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add a heading at the beginning of this page section",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        help_text="Provide a slightly more detailed description of what this carousel section is for",
                                        label="Description",
                                        required=False,
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                ),
                                                (
                                                    "heading",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Add an image subtitle",
                                                        label="Main text",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Add some descriptive information with your image",
                                                        label="Description",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Images",
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "faq_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add a heading at the beginning of this page section",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        label="Description", required=False
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                                (
                                    "faqs",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "question",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Add a simply worded question, like 'How much will it cost?'",
                                                        label="Question",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "answer",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Provide a short answer in no more than a few lines of text",
                                                        label="Answer",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "button",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Text",
                                                                    max_length=100,
                                                                    required=True,
                                                                ),
                                                            ),
                                                            (
                                                                "link",
                                                                wagtail.blocks.URLBlock(
                                                                    label="Link",
                                                                    required=True,
                                                                ),
                                                            ),
                                                        ],
                                                        help_text="Add a link to be followed for more information on that question, feature or product",
                                                        label="URL",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="FAQs",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "feature_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Why our product is best",
                                        help_text="Add a heading at the beginning of this page section",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        help_text="This is the paragraph where you can write more details about your product. Keep it meaningful!",
                                        label="Description",
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Pick an image for the side panel of a feature list",
                                        label="Image",
                                        required=False,
                                    ),
                                ),
                                (
                                    "features",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Feature name. Keep it short, like 'Free Chat' or 'Secure'",
                                                        label="Feature",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Write a few lines about this feature",
                                                        label="Description",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "button",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Text",
                                                                    max_length=100,
                                                                    required=True,
                                                                ),
                                                            ),
                                                            (
                                                                "link",
                                                                wagtail.blocks.URLBlock(
                                                                    label="Link",
                                                                    required=True,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Features",
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "hero_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Manpower Service from a ISO Certified Recruitment Agency",
                                        label="Hero title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        default="The thing we do is take care of your human reosurces",
                                        label="Hero subtitle",
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hero image", required=False
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    max_length=100,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    label="Link", required=True
                                                ),
                                            ),
                                        ],
                                        label="CTA",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "team_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Our illustrious leaders",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        default="Here is a list of our Head Peeps. They look glorious rendered in HTML but are probably just normal, mortal humans.",
                                        label="Description",
                                        required=False,
                                    ),
                                ),
                                (
                                    "members",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.CharBlock(
                                                        label="Name",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        label="Photo", required=False
                                                    ),
                                                ),
                                                (
                                                    "role",
                                                    wagtail.blocks.CharBlock(
                                                        label="Role / Job Title",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "biography",
                                                    wagtail.blocks.TextBlock(
                                                        label="Bio", required=False
                                                    ),
                                                ),
                                                (
                                                    "linkedin",
                                                    wagtail.blocks.URLBlock(
                                                        label="LinkedIn Page",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "twitter",
                                                    wagtail.blocks.URLBlock(
                                                        label="Twitter Page",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Team Members",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "testimonial_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Testimonials",
                                        help_text="Add a heading at the beginning of this page section",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        default="Our users love us. Look at these rave reviews...",
                                        label="Description",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                                (
                                    "testimonials",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Name of the person making the recommendation",
                                                        label="Name",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "role",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Job title of the person making the recommentation, if any",
                                                        label="Role",
                                                        max_length=255,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "organisation",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Name of the organisation the person is part of, if any",
                                                        label="Organisation",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "quote",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="The nice things they have to say",
                                                        label="Quote",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Add either a company logo or a person's mugshot",
                                                        label="Logo/Picture",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "stars",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            (None, "No rating"),
                                                            (0, "0 Stars"),
                                                            (1, "1 Star"),
                                                            (2, "2 Stars"),
                                                            (3, "3 Stars"),
                                                            (4, "4 Stars"),
                                                            (5, "5 Stars"),
                                                        ],
                                                        icon="pick",
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
