# Generated by Django 5.0.1 on 2024-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full time"),
                    ("Part time", "Part time"),
                    ("Contract", "Contract"),
                ],
                max_length=10,
            ),
        ),
    ]
